### ISSUE TITLE
Switch bricked when turning on airplane mode on network install of 10+GB nsp.

### ISSUE THREAD

**Issue by zeronearhero** [digableinc/tinfoil#17] opened 2018-11-15 21:29 UTC
We're reposting this issue due to accidental deletion while cleaning out spam issues.

Original issue body from RepeatingDigits:
> Don't even ask how I found this. I do have a nand backup, but still.

**Comment by zeronearhero** [comment] 2018-11-15 21:40
Unable to reproduce, please provide more information / steps to reproduce the issue.  Here is a video of our test: [https://vimeo.com/301054311](url)

**Comment by Localhorst86** [comment] 2018-11-16 09:55
Maybe it happens when installing to NAND instead of SD?

**Comment by blawar** [comment] 2018-11-20 18:47
Unable to reproduce, closing.  Re-submit if any evidence is encountered.

**Closed by blawar** 2018-11-20 18:47 UTC
